language: php
php:
    - 5.4
    - 5.5
    - 5.6

script: libs/composer/bin/tester tests -s -c tests/php-unix.ini

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    # Install Nette Tester
    - composer self-update
    - composer install --no-interaction --prefer-source
    - mysql -e 'create database testing;'
    - cp tests/AppTests/MyApplication/files/config.local.neon app/config/
    - chmod +x bin/console
    - bin/console joseki:migration:migrate
