<?php

// Load Nette Framework or autoloader generated by Composer
use Nette\Configurator;

require __DIR__ . '/../libs/composer/autoload.php';

$configurator = new Configurator;

// Enable Nette Debugger for error visualisation & logging
$configurator->setDebugMode('127.0.0.1');
$configurator->enableDebugger(__DIR__ . '/../log');

// Specify folder for cache
$configurator->setTempDirectory(__DIR__ . '/../temp');

// Create Dependency Injection container from config.neon file
$configurator->addConfig(__DIR__ . '/config/config.neon');
$configurator->addConfig(__DIR__ . '/../resources/version.neon');
$container = $configurator->createContainer();

return $container;
